export const ActionTypes = {
    TOGGLE_BUILDER_MODE: 'TOGGLE_BUILDER_MODE',
    UPDATE_PLACE_CARDS: 'UPDATE_PLACE_CARDS',
    UPDATE_PLACE_CARDS_WITH_PLACE_STATE: 'UPDATE_PLACE_CARDS_WITH_PLACE_STATE',
    UPDATE_HOTEL_CARDS: 'UPDATE_HOTEL_CARDS',
    UPDATE_TRIP_CARDS: 'UPDATE_TRIP_CARDS',
    UPDATE_PLACE_STYLE_CARDS: 'UPDATE_PLACE_STYLE_CARDS',
    UPDATE_HOTEL_STYLE_CARDS: 'UPDATE_HOTEL_STYLE_CARDS',
    UPDATE_TRIP_STYLE_CARDS: 'UPDATE_TRIP_STYLE_CARDS',
    UPDATE_PLACE_MAPSTYLE_CARDS: 'UPDATE_PLACE_MAPSTYLE_CARDS',
    UPDATE_HOTEL_MAPSTYLE_CARDS: 'UPDATE_HOTEL_MAPSTYLE_CARDS',
    UPDATE_TRIP_MAPSTYLE_CARDS: 'UPDATE_TRIP_MAPSTYLE_CARDS',
    FILTER_CARDS: 'FILTER_CARDS',
    FILTER_PLACE_CARDS_BY_NEXT_HOP : 'FILTER_PLACE_CARDS_BY_NEXT_HOP',
    FILTER_HOTEL_CARDS_BY_PLACENAME : 'FILTER_HOTEL_CARDS_BY_PLACENAME',
    FILTER_STYLE_CARDS: 'FILTER_STYLE_CARDS',
    FILTER_STYLE_CARD: 'FILTER_STYLE_CARD',
    FILTER_MAPSTYLE_CARDS: 'FILTER_MAPSTYLE_CARDS',
    FILTER_MAPSTYLE_CARD: 'FILTER_MAPSTYLE_CARD',
    TOGGLE_ORDERBY_FILTER: 'TOGGLE_ORDERBY_FILTER',
    SET_QUERYTXT_FILTER: 'SET_QUERYTXT_FILTER',
    SET_CARD_TYPE: 'SET_CARD_TYPE',
    TOGGLE_LISTVIEW_VISIBLE: 'TOGGLE_LISTVIEW_VISIBLE',
    TOGGLE_TRIPVIEW_VISIBLE: 'TOGGLE_TRIPVIEW_VISIBLE',
    TOGGLE_DETAILVIEW_VISIBLE: 'TOGGLE_DETAILVIEW_VISIBLE',
    SET_TRIP_VIEW_STATE: 'SET_TRIP_VIEW_STATE',
    SET_TRIP_ITEM: 'SET_TRIP_ITEM',
    SET_TRIP_CARD: 'SET_TRIP_CARD',
    SET_TRIP_JUMPCOUNTER: 'SET_TRIP_JUMPCOUNTER',
    SET_TRIP_CARD_DETAIL_LEVEL: 'SET_TRIP_CARD_DETAIL_LEVEL'
};


export const ApiActionTypes = {
  
    REQUEST_CARDS: 'REQUEST_CARDS',  
    RECEIVE_CARDS: 'RECEIVE_CARDS',
    REQUEST_ITIN_OBJ: 'REQUEST_ITIN_OBJ',
    RECEIVE_ITIN_OBJ: 'RECEIVE_ITIN_OBJ',
    UPDATE_ITIN_OBJ:'UPDATE_ITIN_OBJ'
   
};

 

